# Generated by Django 5.0.7 on 2024-07-27 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="User",
        ),
        migrations.AddField(
            model_name="group",
            name="User",
            field=models.ManyToManyField(
                related_name="user_group", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
