# Generated by Django 5.0.7 on 2024-07-27 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0002_remove_group_user_group_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="User",
            new_name="user",
        ),
    ]
