# Generated by Django 5.0.7 on 2024-07-27 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0003_rename_user_group_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="user",
            new_name="User",
        ),
    ]
