# Generated by Django 5.0.7 on 2024-07-27 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0004_rename_user_group_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="User",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
