# Generated by Django 5.0.7 on 2024-07-26 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=1000)),
                ("answer", models.BooleanField()),
                ("comment", models.CharField(max_length=1000)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.news"
                    ),
                ),
            ],
            options={
                "db_table": "quiz",
            },
        ),
    ]
