# Generated by Django 5.0.7 on 2024-07-28 01:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="todo_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
