# Generated by Django 5.0.7 on 2024-07-28 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_todo_todo_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="user",
            new_name="user_id",
        ),
    ]
