# Generated by Django 5.0.7 on 2024-07-26 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=200)),
                ("profile", models.ImageField(blank=True, upload_to="profiles/")),
                ("nickname", models.CharField(blank=True, max_length=200)),
                ("user_time", models.TimeField(blank=True)),
                ("description", models.CharField(blank=True, max_length=1000)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Wake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("wake_date", models.DateTimeField()),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "wake",
            },
        ),
    ]
