# Generated by Django 5.0.7 on 2024-07-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
