# Generated by Django 5.0.7 on 2024-07-27 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_managers_remove_user_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wake",
            name="wake_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
