# Generated by Django 5.0.7 on 2024-07-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_wake_wake_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="wake",
            name="wake_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
